name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

      # Step 4: Build Sphinx documentation
      - name: Build Sphinx documentation
        uses: ammaraskar/sphinx-action@0.4
        with:
          docs-folder: "docs/"
          build-command: "make html"

      # Step 5 (Optional): Upload built HTML as an artifact
      - name: Upload documentation HTML
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: DocumentationHTML
          path: docs/_build/html/

      # Step 6 (Optional): Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html