name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
      - github-documentation

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify Python version consistent with your matrix

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies using Poetry
        run: |
          poetry install  # This installs all dependencies including those in the dev group

      - name: Build documentation
        run: |
          cd docs  # or your Sphinx root directory
          poetry run sphinx-build -b html . _build/html  # Using poetry run to use the environment

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/_build/html/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
