name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
      - docs

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # Install dependencies using Poetry
      - name: Install project dependencies
        run: |
          poetry install --no-interaction --no-root

      # Build Sphinx documentation
      - name: Build Sphinx documentation
        run: |
          cd docs
          poetry run sphinx-build -b html . _build/html || (echo "Documentation build failed" && exit 1)

      # Upload built documentation as an artifact
      - name: Upload built documentation
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-documentation
          path: docs/_build/html/

      # Deploy to GitHub Pages
      - name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
