name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
      - github-documentation

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies using Poetry
        run: |
          poetry install

      - name: Build documentation
        run: |
          cd docs
          poetry run sphinx-build -b html . _build/html || (echo "Build failed" && exit 1)

      - name: List files for debugging
        run: ls -l docs/_build/html/

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/_build/html/

      - name: Wait for artifact upload
        run: sleep 10

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
